name:  ikuuuCheckin
on:
  push:
    branches: [ main ]
    paths-ignore: 
      - 'README.md'
  schedule:
    - cron: 30 1 * * *
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: install axios
        run: |
          npm install axios
          npm install --save got
          npm install tunnel
      - name: CheckIn
        run: node checkin.js 
        env:
          SENDKEY: ${{ secrets.SENDKEY }}
          HOST: ${{ secrets.HOST }}
          EMAIL: ${{ secrets.EMAIL }}
          PASSWD: ${{ secrets.PASSWD }}

